### ISSUE TITLE
Tests don't compile with Dotty 0.22.0-RC1, due to problems with implicits and macros

### ISSUE THREAD

**Issue by deanwampler** [scalameta/munit#56]
I believe I'm using the same Dotty version, 0.22.0-RC1, as the 0.5.0 release of munit.
 
Consider this example test:

```
import scala.language.implicitConversions // same behavior if present or not.
import munit._
import munit.Location.generate // explicitly added in an attempt to fix an error below...

class MUnitExample extends FunSuite {

  test("A string has a certain length") {
    assertEquals("12345".length, 5)
  }
}
```

It results in the following compilation errors:

```
[error] -- [E007] Type Mismatch Error: .../src/test/scala/foo/bar/munit-example-test.scala:10:7
[error] 10 |  test("A string has a certain length") {
[error]    |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[error]    |       Found:    ("A string has a certain length" : String)
[error]    |       Required: munit.TestOptions
[error]    |       Constraint(
[error]    |        uninstVars = ;
[error]    |        constrained types =
[error]    |        bounds =
[error]    |        ordering =
[error]    |       )
[error]    |       Subtype trace:
[error] -- Error: .../src/test/scala/foo/bar/munit-example-test.scala:11:35
[error] 11 |    assertEquals("12345".length, 5)
[error]    |                                   ^
[error]    |no implicit argument of type munit.Location was found for parameter loc of method assertEquals in trait Assertions.
[error]    |I found:
[error]    |
[error]    |    generate
[error]    |
[error]    |But method generate in trait LocationMacro does not match type munit.Location.
[error]    |
[error]    |The following import might make progress towards fixing the problem:
[error]    |
[error]    |  import munit.Location.generate
[error]    |
[error] -- Error:.../src/test/scala/foo/bar/munit-example-test.scala:12:3
[error] 12 |  }
[error]    |   ^
[error]    |no implicit argument of type munit.Location was found for parameter loc of method test in class FunSuite.
[error]    |I found:
[error]    |
[error]    |    generate
[error]    |
[error]    |But method generate in trait LocationMacro does not match type munit.Location.
[error]    |
[error]    |The following import might make progress towards fixing the problem:
[error]    |
[error]    |  import munit.Location.generate
[error]    |
```
 
I assume that the correct Scala 3 macro for `Location` is being used, but why it thinks the type is wrong I don't understand. The code for the macro looks correct.

I also don't understand enough about implicit resolution in Scala 3 to understand why the conversion to `TestOptions` from `String` isn't invoked. Perhaps it's not actually in scope, even with `import munit._`?

**Comment by olafurpg** [comment]
Thank you for reporting! I'm unable to report by copy-pasting your example in the test suite. The imports should not be necessary, you can `extend munit.FunSuite` without imports and that should work OK.

Can you please include more context?

**Comment by olafurpg** [comment]
PS. I opened https://github.com/scalameta/munit/pull/57 to add a new `def test(name: String)` overload to avoid the need for implicit conversions in the common case. I've been meaning to add this overload for a while

**Comment by deanwampler** [comment]
I created a very small test project that shows these issues. Here are the contents:

### build.sbt

```
name := "mtest-example"

version := "0.0.1"

scalaVersion := "0.22.0-RC1"

libraryDependencies ++= Seq(
    "org.scalameta" %% "munit" % "0.5.0"
  ).map(dep => dep.withDottyCompat(scalaVersion.value))

testFrameworks += new TestFramework("munit.Framework")

lazy val scalacOptionsCommon = Seq(
  "-deprecation",         // Emit warning and location for usages of deprecated APIs.
  "-encoding", "utf-8",   // Specify character encoding used by source files.
  "-unchecked",           // Enable additional warnings where generated code depends on assumptions.
  "-feature",             // Emit warning and location for usages of features that should be imported explicitly.
  "-explain",             // Explain errors in more detail.
  "-explain-types",       // Explain type errors in more detail.
  "-noindent",            // Require classical {...} syntax, indentation is not significant.
  "-old-syntax",          // Require `(...)` around conditions.
  "-strict",              // Use strict type rules, which means some formerly legal code does not typecheck anymore.
  "-migration",           // Emit warning and location for migration issues from Scala 2.
  "-language:Scala2"      // Compile Scala 2 code, highlight what needs updating
)

scalacOptions in Compile := scalacOptionsCommon

scalacOptions in (Compile, console) := scalacOptionsCommon
```

### project/build.properties

```
sbt.version=1.3.7
```

### project/plugins.sbt

```
resolvers ++= Seq(
  "Sonatype Releases" at "https://oss.sonatype.org/content/repositories/releases",
  "Sonatype snapshots" at "https://oss.sonatype.org/content/repositories/snapshots/"
)

addSbtPlugin("ch.epfl.lamp" % "sbt-dotty" % "0.4.0")
```
### src/test/scala/ExampleTest.scala

```
import munit._

class ExampleTest extends FunSuite {

  test("A string has a certain length") {
    assertEquals("12345".length, 5)
  }
}
```

**Comment by deanwampler** [comment]
I just tried removing all those compiler options and I still get the same result, so they don't appear to be the issue.

**Comment by olafurpg** [comment]
What happens if you remove `.map(dep => dep.withDottyCompat(scalaVersion.value))`? It looks like you are pulling in the Scala 2 version instead of 0.22.0-RC1. MUnit is published for Dotty so `withDottyCompat` should not be necessary.

**Comment by deanwampler** [comment]
That was it! I had that map there from my original project, following directions about migrating to Dotty, but it appears I need to use that more carefully. Also, I had to add `import scala.language.implicitConversions` to the test code, but that's understandable.

Thanks for your help!

**Comment by olafurpg** [comment]
Glad you got it working! We have `-language:implicitConversions` enabled in build.sbt so you don't need to add the import everywhere.

**Comment by olafurpg** [comment]
BTW, 0.5.2 is out and it no longer relies on implicit conversions for the most common `test("name") { .. } ` usage. Implicit conversions are still necessary to use extension methods like `test("name".fail) { ... }`

**Comment by deanwampler** [comment]
Thanks. I'll upgrade. I need the import for implicit conversions, because in my project I'm not using the `-language:...` flag. This is for the 3rd edition of Programming Scala and I want to make things like more explicit to the learner. In my own projects, I would use the flag for convenience ;)

**Comment by olafurpg** [comment]
I see, that makes sense. Can you please confirm that the import is no longer needed in 0.5.2? I would like the out-of-the-box experience to require as little ceremony and understanding of advanced features as possible.

**Comment by deanwampler** [comment]
It will compile and run, but I get a warning that I either need to use the `-language:implicitConversions` flag or the import statement. Here is the code where I get that warning:

```
import munit._

class ExampleTest extends FunSuite {

  test("A string has a certain length") {
    assertEquals("12345".length, 5)
  }
}
```

**Comment by deanwampler** [comment]
Also, I removed all the compiler flags in the original `build.sbt` above...

**Comment by olafurpg** [comment]
I'm unable to reproduce the compiler warning when compiling with vanilla Dotty 0.22.0-RC1
```scala
test-workspace/target on 🌱 master
❯ cat example.scala
import munit._

class ExampleTest extends FunSuite {

  test("A string has a certain length") {
    assertEquals("12345".length, 5)
  }
}

test-workspace/target on 🌱 master
❯ dotc -classpath $(coursier fetch org.scalameta:munit_0.22:0.5.2 -p) example.scala
# (compiles without warning)
```

If I add `.fail` like this
```diff
-   test("A string has a certain length") {
+   test("A string has a certain length".fail) {
```

Then I get a message saying there is a feature warning

```sh
❯ dotc -classpath $(cs fetch org.scalameta:munit_0.22:0.5.2 -p) example.scala
there were 1 feature warning(s); re-run with -feature for details
```

**Comment by deanwampler** [comment]
Ah sorry. My mistake; I still had v0.5.0 in my `build.sbt`. When I fixed that, my sample project compiled without this warning.
